import { createWorldState } from "../model.js";

export function createChaisangScenario() {
  return createWorldState({
    id: "chaisang-red-cliff-prelude",
    title: "柴桑：赤壁战前三日",
    time: {
      day: 1,
      phase: "morning",
      tick: 0,
    },
    space: {
      nodes: ["chai-sang-court", "zhou-yu-residence", "river-port"],
      edges: [
        { from: "chai-sang-court", to: "zhou-yu-residence", cost: 1 },
        { from: "chai-sang-court", to: "river-port", cost: 1 },
      ],
    },
    norms: {
      honorCulture: 0.8,
      hierarchyRigidity: 0.75,
      punishmentForBetrayal: 0.9,
      genderRestrictions: 0.7,
    },
    publicOpinion: {
      legitimacy: 0.72,
      alliancePressure: 0.62,
      courtSuspicion: 0.35,
    },
    metadata: {
      playerId: "player",
      scenario: "three-kingdoms",
    },
    agents: [
      {
        id: "sun-quan",
        name: "孙权",
        identity: {
          origin: "江东",
          faction: "吴",
          socialClass: "君主",
          role: "主公",
          location: "柴桑议事厅",
        },
        traits: {
          ambition: 0.8,
          prudence: 0.7,
          empathy: 0.2,
          pride: 0.5,
          loyalty: 0.7,
        },
        drives: {
          survival: 0.9,
          power: 0.8,
          status: 0.7,
          morality: 0.2,
          belonging: 0.4,
        },
        internalState: {
          mood: 0.1,
          stress: 0.55,
          fatigue: 0.2,
          confidence: 0.6,
        },
        resources: {
          money: 100,
          troops: 8000,
          influence: 0.95,
          informationAccess: 0.9,
          time: 1,
        },
        relations: {
          "zhou-yu": { trust: 0.7, respect: 0.8, fear: 0.2, obligation: 0.4 },
          "lu-su": { trust: 0.75, respect: 0.7, obligation: 0.3 },
          "zhang-zhao": { trust: 0.5, respect: 0.7, obligation: 0.5 },
          player: { trust: 0.1, respect: 0.2, fear: 0.05 },
        },
      },
      {
        id: "zhou-yu",
        name: "周瑜",
        identity: {
          origin: "庐江",
          faction: "吴",
          socialClass: "士族",
          role: "都督",
          location: "柴桑议事厅",
        },
        traits: {
          ambition: 0.85,
          prudence: 0.55,
          empathy: 0.1,
          pride: 0.8,
          loyalty: 0.82,
          ruthlessness: 0.45,
        },
        drives: {
          survival: 0.7,
          power: 0.78,
          status: 0.82,
          morality: 0.1,
          revenge: 0.2,
        },
        internalState: {
          mood: 0.15,
          stress: 0.48,
          fatigue: 0.2,
          confidence: 0.72,
        },
        resources: {
          money: 70,
          troops: 5000,
          influence: 0.88,
          informationAccess: 0.75,
          time: 1,
        },
        relations: {
          "sun-quan": { trust: 0.78, respect: 0.88, obligation: 0.4 },
          "lu-su": { trust: 0.42, respect: 0.55 },
          "zhang-zhao": { trust: -0.22, respect: 0.2, resentment: 0.5 },
          player: { trust: -0.3, respect: 0.1, fear: 0.15 },
        },
      },
      {
        id: "lu-su",
        name: "鲁肃",
        identity: {
          origin: "东城",
          faction: "吴",
          socialClass: "士族",
          role: "谋士",
          location: "柴桑议事厅",
        },
        traits: {
          ambition: 0.6,
          prudence: 0.82,
          empathy: 0.55,
          pride: 0.25,
          loyalty: 0.85,
          ruthlessness: 0.1,
        },
        drives: {
          survival: 0.75,
          power: 0.45,
          status: 0.35,
          morality: 0.6,
          belonging: 0.7,
        },
        internalState: {
          mood: 0.3,
          stress: 0.3,
          fatigue: 0.1,
          confidence: 0.62,
        },
        resources: {
          money: 40,
          troops: 800,
          influence: 0.64,
          informationAccess: 0.82,
          time: 1,
        },
        relations: {
          "sun-quan": { trust: 0.82, respect: 0.73, obligation: 0.35 },
          "zhou-yu": { trust: 0.58, respect: 0.72 },
          "zhang-zhao": { trust: 0.2, respect: 0.45 },
          player: { trust: 0.42, respect: 0.35 },
        },
      },
      {
        id: "zhang-zhao",
        name: "张昭",
        identity: {
          origin: "彭城",
          faction: "吴",
          socialClass: "士族",
          role: "朝臣元老",
          location: "柴桑议事厅",
        },
        traits: {
          ambition: 0.45,
          prudence: 0.88,
          empathy: 0.1,
          pride: 0.72,
          loyalty: 0.62,
          ruthlessness: 0.52,
        },
        drives: {
          survival: 0.82,
          power: 0.38,
          status: 0.55,
          morality: 0.3,
          belonging: 0.42,
        },
        internalState: {
          mood: -0.1,
          stress: 0.45,
          fatigue: 0.15,
          confidence: 0.58,
        },
        resources: {
          money: 55,
          troops: 100,
          influence: 0.79,
          informationAccess: 0.86,
          time: 1,
        },
        relations: {
          "sun-quan": { trust: 0.55, respect: 0.72, obligation: 0.42 },
          "zhou-yu": { trust: -0.3, respect: 0.15, resentment: 0.65 },
          "lu-su": { trust: 0.15, respect: 0.3 },
          player: { trust: -0.42, respect: -0.1, fear: 0.08 },
        },
      },
      {
        id: "player",
        name: "玩家使者",
        identity: {
          origin: "刘备阵营",
          faction: "客方",
          socialClass: "宾客",
          role: "使者",
          location: "柴桑议事厅",
        },
        traits: {
          ambition: 0.52,
          prudence: 0.65,
          empathy: 0.42,
          pride: 0.2,
          loyalty: 0.5,
          ruthlessness: 0.18,
        },
        drives: {
          survival: 0.8,
          power: 0.35,
          status: 0.3,
          morality: 0.42,
          belonging: 0.25,
        },
        internalState: {
          mood: 0.1,
          stress: 0.4,
          fatigue: 0.12,
          confidence: 0.45,
        },
        resources: {
          money: 12,
          troops: 0,
          influence: 0.32,
          informationAccess: 0.45,
          time: 1,
        },
        relations: {
          "sun-quan": { trust: 0.24, respect: 0.45, fear: 0.2 },
          "zhou-yu": { trust: -0.35, respect: 0.18, fear: 0.4 },
          "lu-su": { trust: 0.5, respect: 0.42, obligation: 0.1 },
          "zhang-zhao": { trust: -0.45, respect: 0.05, fear: 0.22 },
        },
      },
    ],
  });
}
